### ISSUE TITLE
Plugin not functional on SpongeForge 5

### ISSUE THREAD

**Issue by Magi1053** [Redrield/chatcoloursplus#2]
```[10:19:39] [Server thread/ERROR] [Sponge/]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=chatcoloursplus, name=ChatColoursPlus, version=1.2, source=/home/minecraft/runtime/mods/$ponge_ChatColoursPlus-1.0-all.jar}
java.lang.UnsupportedOperationException: Key not supported. Key: Key{Value:Value<Text>, Query: colour}
	at org.spongepowered.api.data.value.ValueContainer.getOrNull(ValueContainer.java:109) ~[ValueContainer.class:1.10.2-2254-5.2.0-BETA-2231]
	at com.redrield.chatcoloursplus.ChatColoursPlus.onPlayerChat(ChatColoursPlus.kt:53) ~[ChatColoursPlus.class:?]
	at org.spongepowered.common.event.listener.ChatListener_ChatColoursPlus_onPlayerChat3.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2254-5.2.0-BETA-2231]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2231]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:271) [SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2231]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:618) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) [EventBus.class:?]
	at noppes.npcs.entity.EntityNPCInterface.saySurrounding(EntityNPCInterface.java:893) [EntityNPCInterface.class:?]
	at noppes.npcs.ai.EntityAIWander.func_75251_c(EntityAIWander.java:123) [EntityAIWander.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:113) [tr.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773) [sg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [sg.class:?]
	at noppes.npcs.entity.EntityNPCInterface.func_70636_d(EntityNPCInterface.java:392) [EntityNPCInterface.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [sg.class:?]
	at noppes.npcs.entity.EntityNPCInterface.func_70071_h_(EntityNPCInterface.java:277) [EntityNPCInterface.class:?]
	at noppes.npcs.entity.EntityCustomNpc.func_70071_h_(EntityCustomNpc.java:35) [EntityCustomNpc.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:156) [TrackingUtil.class:1.10.2-2254-5.2.0-BETA-2231]
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjn000(WorldServer.java:2810) [ls.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:4071) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:5954) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2153) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]```

**Comment by Redrield** [comment]
Couldn't reproduce the issue with latest SpongeForge 5.2.0 build for 1.10.2.
